//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeethCabinet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RDV
    {
        public int RdvID { get; set; }
        public int PatientID { get; set; }
        public int PersonnelID { get; set; }
        public Nullable<System.DateTime> DateHeureRdv { get; set; }
        public string Motif { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Personnel Personnel { get; set; }
    }
}
